name: E2E on Release
on:
  release:
    types: [published]
jobs:
  deploy-n-e2e:
    name: "Deploy to KinD and E2E"
    runs-on: ubuntu-latest
    steps:
      - name: Download deploy.e2e.yaml from Release
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          DOWNLOAD_URL: ${{ github.event.release.assets[0].browser_download_url }}
        run: |
          echo "browser_download_urls - ${{ toJson(github.event.release.assets.*.browser_download_url) }}"
          echo "$RELEASE_TAG"
          echo "Downloading $DOWNLOAD_URL"
          curl -O -L $DOWNLOAD_URL
      - name: "Create cluster using KinD"
        id: kind
        uses: engineerd/setup-kind@v0.1.0
        # with:
        #   config: .github/kubernetes/kind.yaml
      - name: "Deploy deploy.e2e.yaml to KinD"
        id: local-path
        run: |
          export KUBECONFIG="$(kind get kubeconfig-path)"
          echo "waiting for nodes to be ready ..."
          kubectl wait --for=condition=Ready nodes --all --timeout=5m
          echo "nodes ..."
          kubectl get nodes
          echo "cluster-info ..."
          kubectl cluster-info
          echo "installing e2e overlay..."
          kubectl apply -f deploy.e2e.yaml
          echo "waiting for pods to be ready ..."
          kubectl wait --for=condition=Ready pods --all --timeout=5m
          kubectl get pods
      - name: Run e2e tests
        env:
          # MICRO_REGISTRY: memory
          # MICRO_SELECTOR: static
          MICRO_PROXY_ADDRESS: "localhost:8888"
        run: |
          # make test-e2e
          # e2e/test.sh
          echo "TODO: e2e tests"
